### ISSUE TITLE
Would it be possible to ignore activity that are already liked?

### ISSUE THREAD

**Issue by Kayizoku** [taichikuji/AniLiker#14]
Hi, I use your script and quite like it. I do have some ideas for other things too. For one, would it be possible to ignore activity from a user that is already liked? If not, it dislikes those activities and that can be annoying. Another thing is if you could choose activity type yourself. I would rather it only like list activities and not text or messages if that makes sense. Thank you in advance ^^

**Comment by taichikuji** [comment]
Hello! First of all, thank you very much for creating an issue!

This issue (ignore activities that have been already liked) has already been solved, see #11 .

The suggestion you're making (choosing what kind of posts you can like) is interesting and can definitely be done. I will look into it and see if there's an easy fix I can make for it! The idea I'm thinking is to implement 3 different queries and implement it based on an option chosen when running the script. Could do it either that way or through the dotenv file. Will see which way is the most user-friendly.

Will post more here as I look into it! 😄

**Comment by taichikuji** [comment]
I found a way of doing it! Will push as soon as I test it thoroughly

**Comment by taichikuji** [comment]
Will update the Wiki now!

**Comment by taichikuji** [comment]
I created the Wiki page [How to use the QUERY_OPTIONS in AniLiker](https://github.com/taichikuji/AniLiker/wiki/How-to-use-the-QUERY_OPTIONS-in-AniLiker). Hopefully it's easy to understand!
